name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: environments/dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::055657146366:role/financial-sre-github-actions-role
          aws-region: us-east-1 
      - name: Show actual GitHub OIDC claims
        shell: bash
        run: |
          TOKEN_RESPONSE=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          ID_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.value')

          PAYLOAD=$(echo "$ID_TOKEN" | cut -d '.' -f2)

          # JWT base64url padding
          case $((${#PAYLOAD} % 4)) in
            2) PAYLOAD="${PAYLOAD}==" ;;
            3) PAYLOAD="${PAYLOAD}=" ;;
          esac

          echo "$PAYLOAD" \
            | tr '_-' '/+' \
            | base64 -d 2>/dev/null \
            | jq '{iss, aud, sub, repository, repository_id, repository_owner, repository_owner_id, event_name, ref}'     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.5
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      - name: Build Lambda deployment packages
        run: |
          cd ../../services/transaction-api
          zip transaction-api.zip lambda_function.py

          cd ../transaction-worker
          zip transaction-worker.zip lambda_function.py

      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
       